repos:
-   repo: local
    hooks:
    -   id: pytest
        name: Run tests with pytest
        entry: uv run pytest
        language: system
        stages: [pre-push]
        pass_filenames: false
        always_run: true        
    -   id: branch-protection
        name: Block direct pushes to protected branches
        entry: utils/branch_protection.sh
        language: script
        stages: [pre-push]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
    -   id: commitizen
        stages: [commit-msg]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.0
    hooks:
    # Run the linter.
      - id: ruff-check
        args: [ --fix ]
        stages: [pre-commit]
    # Run the formatter.
      - id: ruff-format
        stages: [pre-commit]